name = "heady-auth-service-prod-worker"
main = "src/index.ts"
compatibility_date = "2026-02-09"

[env.production]
workers_dev = true
route = "auth.headyconnection.org/*"
[vars]
HEADY_API_KEY = "{{ secrets.HEADY_API_KEY }}"
ADMIN_TOKEN = "{{ secrets.ADMIN_TOKEN }}"
BENEFICIAL = "{{ secrets.BENEFICIAL }}"
