apiVersion: 1

datasources:
  - name: Prometheus-AI
    type: prometheus
    access: proxy
    url: http://prometheus-ai:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
